[platformio]
lib_dir = lib

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
board_build.partitions = min_spiffs.csv
framework = arduino

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.6
    bblanchon/ArduinoJson @ ^7

board_build.filesystem = littlefs

build_flags =
    -DCORE_DEBUG_LEVEL=0

monitor_speed = 115200

[env:t_internet_poe]
upload_speed = 115200

[env:t_internet_poe_ota]
upload_protocol = espota
upload_port = dsc.local
