[platformio]
src_dir = src/DSC-HomeKit-Ethernet
lib_dir = lib

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
board_build.partitions = huge_app.csv
framework = arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0        ; suppress Arduino-layer IDF logs
    -DCONFIG_LOG_DEFAULT_LEVEL=0 ; suppress ESP-IDF component logs (ETH, lwIP, ets_printf)

upload_speed = 115200

monitor_speed = 115200
